### PR TITLE
feat: three cards divination service implementation

### PR DESCRIPTION
**Pull request by aledobrean**

### CODE REVIEW

**Comment by giraffeingreen** [comment]
No need forr html

**Comment by giraffeingreen** [comment]
@CodiumAI-Agent /review

**Comment by giraffeingreen** [comment]
@CodiumAI-Agent  /describe

**Comment by giraffeingreen** [comment]
@CodiumAI-Agent  /improve --extended

**Comment by aledobrean** [comment]
@CodiumAI-Agent /improve

**Comment by aledobrean** [comment]
@CodiumAI-Agent /improve

**Comment by aledobrean** [comment]
@CodiumAI-Agent /improve

**Pull request merged**
